name = "tfa-sync"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "SYNC"
id = "PLACEHOLDER_CREATE_KV_NAMESPACE"

[vars]
SITE_URL = "https://thefourthangle.pages.dev"
