name = "tfa-sync"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "SYNC"
id = "a8d70bc33ea94ede93a345f75b6c6e6a"

[vars]
SITE_URL = "https://thefourthangle.pages.dev"
